import type { BlogPost } from './types'

const author = {
  author: 'Leon',
  authorRole: 'Osobni trener i vlasnik UnitLift-a',
} as const

export const blogPostsHr2026Rest: BlogPost[] = [
  {
    slug: 'kako-postati-online-personal-trener',
    title: 'Kako početi raditi kao online osobni trener u Hrvatskoj',
    excerpt: 'Korak po korak: što trebaš, kako naći prve klijente i kako organizirati rad od prvog dana.',
    category: 'Vodič',
    categorySlug: 'vodic',
    readTime: 8,
    publishedAt: '19. travnja 2026.',
    ...author,
    metaTitle: 'Kako postati online osobni trener u Hrvatskoj | Vodič',
    metaDescription: 'Korak po korak: što trebaš, kako naći prve klijente i kako organizirati rad od prvog dana.',
    cta: {
      text: 'Kad stignu prvi klijenti, trebat će ti jasan sustav. Probaj UnitLift 14 dana besplatno, postavljanje traje oko 5 minuta.',
      btn: 'Kreni besplatno i dodaj prve klijente →',
      href: '/cijene',
    },
    content: [
      { type: 'paragraph', text: 'Online osobni trener radi s klijentima preko mobitela i poruka. Ovaj tekst je za trenere koji tek počinju i žele postaviti rad čisto od prvog dana.' },
      { type: 'paragraph', text: 'Prolazimo što ti zaista treba na startu, kako dobiti prve klijente i koje alate koristiti. Bez teorije, samo praktični koraci.' },
      { type: 'internal-link', text: '→ Devet taktika za veću bazu klijenata', href: '/hr/blog/kako-povecati-bazu-klijenata' },
      { type: 'internal-link', text: '→ Kako postaviti cijene bez podcjenjivanja', href: '/hr/blog/kako-postaviti-cijene' },

      { type: 'heading', text: 'Što trebaš prije prvog klijenta' },
      { type: 'list', items: [
        'Jasna ponuda: jedan paket, jedna cijena, rok trajanja',
        'Način naplate: IBAN, PayPal ili online plaćanje',
        'Pravna forma: obrt ili j.d.o.o. ako to misliš ozbiljno',
        'Mjesto gdje će klijent primati plan i slati check-in',
      ]},
      { type: 'paragraph', text: 'Web stranica i logo nisu obavezni na startu. Mogu čekati dok ne dobiješ prve dvije ili tri potvrde da ljudi žele plaćati.' },

      { type: 'heading', text: 'Gdje dobiti prve klijente' },
      { type: 'paragraph', text: 'Prvi klijenti najčešće dolaze iz kruga koji te već zna. Javi se ljudima koji su ti već rekli da ih zanima trening.' },
      { type: 'list', items: [
        'Napiši listu od 20 osoba iz teretane, posla ili obitelji',
        'Javi im da pokrećeš online program i nudiš probni paket',
        'Traži dva ili tri klijenta za testiranje, uz manju cijenu',
        'Nakon mjesec dana traži preporuke i kratki testimonijal',
      ]},
      { type: 'internal-link', text: '→ Onboarding: što s novim klijentom u prvom tjednu', href: '/hr/blog/onboarding-novi-klijent' },

      { type: 'heading', text: 'Minimalni alati za start' },
      { type: 'list', items: [
        'Jedan način slanja računa ili potvrde o uplati',
        'Jedno mjesto gdje klijent vidi plan treninga',
        'Jedan kanal za check-in, istog dana svaki tjedan',
        'Jedna aplikacija za poruke s klijentima',
      ]},
      { type: 'paragraph', text: 'Ako plan, uplate i check-in vodiš u četiri različite aplikacije, rad postaje naporan već kod pet klijenata. Jedan alat koji pokriva sve štedi sate.' },

      { type: 'heading', text: 'Kad posao postane ozbiljan' },
      { type: 'paragraph', text: 'Kod tri ili više klijenata više nije “hobi navečer”. Tada izračunaj koliko vremena trošiš na jednog klijenta i koliko ti ostaje za dolazak novih ljudi.' },
      { type: 'internal-link', text: '→ Koliko zarađivati kao online trener', href: '/hr/blog/kako-zaraditi-vise-kao-online-fitness-trener' },

      { type: 'heading', text: 'Česta pitanja' },
      { type: 'subheading', text: 'Moram li odmah imati stranicu i logo?' },
      { type: 'paragraph', text: 'Ne. Dovoljno je da ljudi mogu kupiti paket i primiti jasne upute. Stranica dolazi kasnije.' },
      { type: 'subheading', text: 'Je li certifikat obavezan?' },
      { type: 'paragraph', text: 'Ovisi o poslodavcu ili teretani s kojom radiš. Za samostalni rad provjeri trenutnu regulativu.' },
      { type: 'subheading', text: 'Mogu li prebaciti klijente iz teretane online?' },
      { type: 'paragraph', text: 'Da. To je najčešći put i najlakši prelazak jer već imaš povjerenje.' },
      { type: 'subheading', text: 'Koliko naplatiti na startu?' },
      { type: 'paragraph', text: 'Između 50 i 80 eura mjesečno za početni paket je realan raspon na hrvatskom tržištu.' },
      { type: 'subheading', text: 'Što s porezom?' },
      { type: 'paragraph', text: 'Nađi knjigovođu od početka. Pravna forma i porez nisu komplicirani kad imaš jednu osobu koja to vodi.' },
    ],
  },
  {
    slug: 'sto-je-check-in-online-coaching',
    title: 'Što je check-in u online coachingu i kako ga postaviti',
    excerpt: 'Check-in je tjedni pregled napretka klijenta. Objašnjavamo što treba sadržavati i kako ga postaviti od prvog dana.',
    category: 'Vodič',
    categorySlug: 'vodic',
    readTime: 7,
    publishedAt: '19. travnja 2026.',
    ...author,
    metaTitle: 'Što je check-in u online coachingu? Vodič za trenere',
    metaDescription: 'Check-in je tjedni pregled napretka klijenta. Objašnjavamo što treba sadržavati i kako ga postaviti od prvog dana.',
    cta: {
      text: 'U UnitLiftu klijent šalje check-in iz mobilne aplikacije. Podsjetnici i povijest su na jednom mjestu, bez lova po chatu.',
      btn: 'Vidi kako check-in radi u UnitLiftu →',
      href: '/kako-radi',
    },
    content: [
      { type: 'paragraph', text: 'Check-in je kratak pregled napretka klijenta jednom tjedno. Klijent javlja što je odradio, kako se osjeća i ima li problema.' },
      { type: 'paragraph', text: 'Bez check-ina online coaching postaje slanje planova u prazno. S dobrim check-inom vidiš trendove i reagiraš na vrijeme.' },
      { type: 'internal-link', text: '→ Pet savjeta za bolje check-in razgovore', href: '/hr/blog/savjeti-za-check-in-razgovore' },
      { type: 'internal-link', text: '→ Kako zadržati klijenta dulje od tri mjeseca', href: '/hr/blog/kako-zadrzati-online-klijenta' },

      { type: 'heading', text: 'Što check-in treba sadržavati' },
      { type: 'list', items: [
        'Težina i jedna mjera opsega, ako su dio plana',
        'Kratka ocjena energije, sna i razine stresa',
        'Koliko treninga je odrađeno u tjednu',
        'Kratki komentar o prehrani, ako je dio paketa',
        'Jedno slobodno polje za klijenta',
      ]},
      { type: 'paragraph', text: 'Pet do sedam pitanja je dovoljno. Manje znači slaba slika, više znači da će klijent preskočiti odgovore.' },

      { type: 'heading', text: 'Kada tražiti check-in' },
      { type: 'paragraph', text: 'Odaberi isti dan i isto vrijeme svaki tjedan. Nedjelja uvečer ili ponedjeljak ujutro najčešće rade najbolje.' },
      { type: 'paragraph', text: 'Postavi automatski podsjetnik. Bez toga stopa odgovora pada ispod 50 posto, s podsjetnikom raste na preko 80.' },

      { type: 'heading', text: 'Kako odgovoriti na check-in' },
      { type: 'paragraph', text: 'Odgovor pošalji unutar 24 sata. Klijent koji čeka tri dana na odgovor osjeća se zaboravljenim.' },
      { type: 'list', items: [
        'Komentiraj jedan konkretan podatak iz check-ina',
        'Potvrdi plan za idući tjedan ili predloži promjenu',
        'Postavi jedno kratko pitanje ako nešto nije jasno',
      ]},
      { type: 'internal-link', text: '→ Kako planovi treninga izgledaju za online klijente', href: '/hr/blog/planovi-treninga-online-klijenti' },

      { type: 'heading', text: 'Check-in i naplata idu zajedno' },
      { type: 'paragraph', text: 'Ako klijent plaća mjesec unaprijed, a check-in ne šalje tjedno, teško je ići u dublje promjene plana. Veži check-in uz paket.' },
      { type: 'internal-link', text: '→ Kako organizirati 20 online klijenata', href: '/hr/blog/kako-organizirati-online-klijente' },

      { type: 'heading', text: 'Česta pitanja' },
      { type: 'subheading', text: 'Je li check-in isto što i pitanje “kako si”?' },
      { type: 'paragraph', text: 'Nije. Check-in ima fiksna pitanja koja se ponavljaju, pa vidiš trend kroz više tjedana.' },
      { type: 'subheading', text: 'Što ako klijent dva tjedna ne pošalje check-in?' },
      { type: 'paragraph', text: 'Javi se direktno. Najčešći razlozi su prezauzetost ili to da je klijent izgubio motivaciju.' },
      { type: 'subheading', text: 'Trebam li tražiti slike napretka?' },
      { type: 'paragraph', text: 'Ako je cilj promjena izgleda, da. Dogovori istu pozu i isto svjetlo svaki put.' },
      { type: 'subheading', text: 'Što ako klijent ne želi vagati?' },
      { type: 'paragraph', text: 'Dogovori drugu mjeru, najčešće opseg struka. Isti postupak svaki tjedan.' },
      { type: 'subheading', text: 'Je li tri pitanja dovoljno?' },
      { type: 'paragraph', text: 'Može biti, ali bolje je pet do sedam istih pitanja nego dvadeset koje klijent popuni na pola.' },
    ],
  },
  {
    slug: 'planovi-treninga-online-klijenti',
    title: 'Kako izgledaju planovi treninga za online klijente',
    excerpt: 'Što treba sadržavati dobar online plan treninga, kako ga poslati klijentu i što klijent vidi na svojoj strani.',
    category: 'Vodič',
    categorySlug: 'vodic',
    readTime: 7,
    publishedAt: '18. travnja 2026.',
    ...author,
    metaTitle: 'Planovi treninga za online klijente - kako ih napraviti',
    metaDescription: 'Što treba sadržavati dobar online plan treninga, kako ga poslati klijentu i što klijent vidi na svojoj strani.',
    cta: {
      text: 'U UnitLiftu klijent vidi plan iz mobitela, bez PDF-ova. Postavi prvi plan u par minuta i probaj 14 dana besplatno.',
      btn: 'Isprobaj UnitLift 14 dana besplatno →',
      href: '/cijene',
    },
    content: [
      { type: 'paragraph', text: 'Dobar online plan treninga klijent može otvoriti iz mobitela i odmah znati što raditi. Bez dugih tablica i bez traženja po chatu.' },
      { type: 'paragraph', text: 'U ovom tekstu prolazimo što plan treba sadržavati, kako ga poslati i kada ga mijenjati.' },
      { type: 'internal-link', text: '→ Što je check-in i kako ga povezati s planom', href: '/hr/blog/sto-je-check-in-online-coaching' },
      { type: 'internal-link', text: '→ Koliko vremena odlazi na 10, 20 i 30 klijenata', href: '/hr/blog/koliko-vremena-za-online-klijente' },

      { type: 'heading', text: 'Što plan za jedan tjedan treba sadržavati' },
      { type: 'list', items: [
        'Cilj tjedna napisan u jednoj rečenici',
        'Vježbe, setovi, ponavljanja i pauze',
        'Kratku uputu za tehniku ili link na video',
        'Zamjensku vježbu ako nema opreme',
        'Jasno mjesto gdje klijent unosi rezultat',
      ]},
      { type: 'paragraph', text: 'Ako klijent ne zna što je danas na redu unutar 30 sekundi, plan je predugačak. Skrati, ne dodaj.' },

      { type: 'heading', text: 'Kada mijenjati plan' },
      { type: 'paragraph', text: 'Ako dva check-ina kažu da klijent ne stigne, smanji volumen. Ako tri tjedna ide glatko, povećaj opterećenje.' },
      { type: 'paragraph', text: 'Velike promjene svakih šest tjedana, male korekcije svaki tjedan. Izbjegavaj slanje novog bloka svakog ponedjeljka.' },
      { type: 'internal-link', text: '→ Kako zadržati klijenta kad se život upleće', href: '/hr/blog/kako-zadrzati-online-klijenta' },

      { type: 'heading', text: 'Kako predati plan klijentu' },
      { type: 'paragraph', text: 'Najgore je plan slati kao PDF preko WhatsApp-a. Klijent ga izgubi u razgovoru i opet pita gdje je.' },
      { type: 'list', items: [
        'Aplikacija za coaching gdje klijent otvori plan s mobitela',
        'Jasan raspored: ponedjeljak - noge, utorak - leđa i slično',
        'Video ili slika za vježbu koju klijent prvi put radi',
        'Napomena kad klijent ne može trenirati tri puta tjedno',
      ]},
      { type: 'internal-link', text: '→ Kako organizirati online klijente u jedan sustav', href: '/hr/blog/kako-organizirati-online-klijente' },

      { type: 'heading', text: 'Česta pitanja' },
      { type: 'subheading', text: 'Trebam li video za svaku vježbu?' },
      { type: 'paragraph', text: 'Ne. Video treba samo za vježbe gdje klijentova tehnika nije sigurna ili za nove vježbe.' },
      { type: 'subheading', text: 'Koliko unaprijed slati plan?' },
      { type: 'paragraph', text: 'Dva do tri tjedna unaprijed. Tako ne sastavljaš nove planove u zadnji čas.' },
      { type: 'subheading', text: 'Što s klijentom koji putuje?' },
      { type: 'paragraph', text: 'Pripremi kratku verziju plana za hotel ili park. Zamijeni velike vježbe s bodyweight varijantom.' },
      { type: 'subheading', text: 'Što ako klijent preskoči trening?' },
      { type: 'paragraph', text: 'Prvo pitaj na check-inu zašto. Ako je razlog život, prilagodi plan. Ako je motivacija, razgovaraj direktno.' },
      { type: 'subheading', text: 'Trebam li raditi test snage?' },
      { type: 'paragraph', text: 'Samo ako radiš s naprednim klijentima. Za većinu klijenata dovoljno je pratiti opterećenje iz tjedna u tjedan.' },
    ],
  },
  {
    slug: 'kako-zadrzati-online-klijenta',
    title: 'Kako zadržati online klijenta dulje od tri mjeseca',
    excerpt: 'Zašto klijenti odustaju nakon dva ili tri mjeseca i što konkretno možeš napraviti da ostanu dulje.',
    category: 'Klijenti',
    categorySlug: 'klijenti',
    readTime: 7,
    publishedAt: '18. travnja 2026.',
    ...author,
    metaTitle: 'Kako zadržati online klijenta - retention vodič',
    metaDescription: 'Zašto klijenti odustaju nakon 2–3 mjeseca i što konkretno možeš napraviti da ostanu dulje.',
    cta: {
      text: 'U UnitLiftu vidiš tko kasni s check-inom i tko nije uplatio. Manje propusta, dulje zadržavanje. Probaj 14 dana besplatno.',
      btn: 'Kreni besplatno i dodaj prve klijente →',
      href: '/cijene',
    },
    content: [
      { type: 'paragraph', text: 'Većina klijenata ne odustaje zbog lošeg plana. Odustaju jer nemaju osjećaj da napreduju i jer ne vide gdje ide sljedećih mjesec dana.' },
      { type: 'paragraph', text: 'U ovom tekstu prolazimo zašto se to događa u drugom i trećem mjesecu i što napraviti da klijent ostane šest ili dvanaest mjeseci.' },
      { type: 'internal-link', text: '→ Kako postaviti check-in koji daje pravu sliku', href: '/hr/blog/sto-je-check-in-online-coaching' },
      { type: 'internal-link', text: '→ Pet savjeta za bolje check-in razgovore', href: '/hr/blog/savjeti-za-check-in-razgovore' },

      { type: 'heading', text: 'Što se događa u drugom i trećem mjesecu' },
      { type: 'paragraph', text: 'Prvi mjesec klijent je pun motivacije. Drugi mjesec nastupa rutina. Treći mjesec traži jasno gdje ide sljedeća faza.' },
      { type: 'paragraph', text: 'Ako ne dobije novu fazu i jasan plan idućih tjedana, tiho odustane. Najavu prekida dobiješ zadnji.' },

      { type: 'heading', text: 'Rani znakovi da klijent odustaje' },
      { type: 'list', items: [
        'Dva tjedna zaredom bez check-ina',
        'Kratki odgovori tipa “super, nastavljam”',
        'Preskočeni treninzi bez objašnjenja',
        'Kašnjenje s uplatom više od tri dana',
      ]},
      { type: 'paragraph', text: 'Na svaki od ovih znakova reagiraj isti tjedan. Ne čekaj sljedeći ciklus plaćanja.' },

      { type: 'heading', text: 'Što radi za dulje zadržavanje' },
      { type: 'list', items: [
        'Jasno postavljena faza: sljedećih četiri tjedna radimo ovo',
        'Jedan mali razgovor mjesečno, ne samo tekstualni odgovori',
        'Vidljiv napredak: graf, fotografija prije i poslije, brojevi',
        'Jasan raspored uplata, bez neugodnih podsjećanja',
      ]},

      { type: 'heading', text: 'Kad klijent odustane' },
      { type: 'paragraph', text: 'Pristojan razgovor, bez krivnje. Pitaj što bi se trebalo drugačije i ponudi manju uslugu za kasnije.' },
      { type: 'paragraph', text: 'Nakon četiri do šest tjedana možeš poslati kratku poruku. Dio ljudi se vrati.' },

      { type: 'heading', text: 'Česta pitanja' },
      { type: 'subheading', text: 'Što ako klijent kasni s uplatom?' },
      { type: 'paragraph', text: 'Pošalji jasan podsjetnik jednom. Ako ne plati tri dana, dogovori razgovor. Bez drame, ali bez otezanja.' },
      { type: 'subheading', text: 'Što kad motivacija padne?' },
      { type: 'paragraph', text: 'Smanji volumen treninga. Ubaci jedan lakši tjedan. Veži plan za konkretan događaj.' },
      { type: 'subheading', text: 'Vrijedi li pokušati vratiti klijenta?' },
      { type: 'paragraph', text: 'Pokušaj jednom, nakon tri do četiri tjedna. Ako nema odgovora, nemoj inzistirati.' },
    ],
  },
  {
    slug: 'koliko-vremena-za-online-klijente',
    title: 'Koliko vremena tjedno treba za 10, 20 i 30 online klijenata',
    excerpt: 'Stvarni brojevi: koliko sati tjedno odlazi na administraciju, planove i komunikaciju za svakih 10 klijenata.',
    category: 'Produktivnost',
    categorySlug: 'produktivnost',
    readTime: 6,
    publishedAt: '17. travnja 2026.',
    ...author,
    metaTitle: 'Koliko vremena treba za online klijente? Stvarni brojevi',
    metaDescription: 'Stvarni brojevi: koliko sati tjedno odlazi na administraciju, planove i komunikaciju za svakih 10 klijenata.',
    cta: {
      text: 'UnitLift drži planove, check-in, poruke i plaćanja na jednom ekranu. Probaj 14 dana besplatno i oslobodi sate tjedno.',
      btn: 'Kreni besplatno i dodaj prve klijente →',
      href: '/cijene',
    },
    content: [
      { type: 'paragraph', text: 'Koliko sati tjedno troši prosječan online trener? Ovisi o broju klijenata, ali i o sustavu koji koristi.' },
      { type: 'paragraph', text: 'U ovom tekstu dajemo realne brojeve za 10, 20 i 30 klijenata. Brojevi su iz razgovora s trenerima koje pratimo.' },
      { type: 'internal-link', text: '→ Kako organizirati 20 online klijenata', href: '/hr/blog/kako-organizirati-online-klijente' },
      { type: 'internal-link', text: '→ Što automatizirati u online coachingu', href: '/hr/blog/automatizacija-u-coachingu' },

      { type: 'heading', text: 'Gdje vrijeme zaista odlazi' },
      { type: 'list', items: [
        'Planovi treninga i prilagodbe: 2 do 4 sata tjedno',
        'Planovi prehrane, ako su u paketu: 1 do 3 sata',
        'Čitanje i odgovori na check-in: 1.5 do 3 sata',
        'Poruke i brza pitanja klijenata: 1 do 3 sata',
        'Administracija i uplate: 0.5 do 2 sata',
      ]},
      { type: 'paragraph', text: 'Brojevi su za blok od 10 klijenata. Gornji raspon vrijedi ako koristiš više nepovezanih alata.' },

      { type: 'heading', text: 'Ukupno po broju klijenata' },
      { type: 'list', items: [
        '10 klijenata: između 5 i 8 sati tjedno',
        '20 klijenata: između 10 i 15 sati tjedno',
        '30 klijenata: između 16 i 24 sata tjedno',
      ]},
      { type: 'paragraph', text: 'Ako si iznad ovih brojeva, problem nije količina klijenata. Problem je što alat ili sustav ne radi dobro.' },

      { type: 'heading', text: 'Što radi najveću razliku' },
      { type: 'paragraph', text: 'Predlošci planova koje samo prilagodiš. Standardna pitanja za check-in. Automatski podsjetnici. Sve troje može skratiti tjedan za više od pet sati.' },
      { type: 'internal-link', text: '→ Cijene i paketi: kako postaviti', href: '/hr/blog/kako-postaviti-cijene' },

      { type: 'heading', text: 'Kad trebaš pomoć' },
      { type: 'paragraph', text: 'Kad tjedno trošiš više od 30 sati, vrijeme je za promjenu. Prvo sustav, onda asistent. Ne obratno.' },

      { type: 'heading', text: 'Česta pitanja' },
      { type: 'subheading', text: 'Je li 30 klijenata održivo samostalno?' },
      { type: 'paragraph', text: 'Jest, ali samo s dobrim sustavom. Bez sustava trideset klijenata pojede 40 sati tjedno.' },
      { type: 'subheading', text: 'Gdje najviše vremena curi?' },
      { type: 'paragraph', text: 'Kopiranje podataka između alata i traženje starih planova. Predlošci i jedan alat rješavaju 80 posto problema.' },
      { type: 'subheading', text: 'Je li jedan sat dnevno dovoljan?' },
      { type: 'paragraph', text: 'Za 10 klijenata jest. Za 20 klijenata trebaš dva sata dnevno ili jaku koncentraciju u dva bloka.' },
      { type: 'subheading', text: 'Kad trebam asistenta?' },
      { type: 'paragraph', text: 'Kad rad s klijentima i administracija prelaze 25 do 30 sati tjedno, a sustav je već optimiziran.' },
      { type: 'subheading', text: 'Utječe li alat stvarno na vrijeme?' },
      { type: 'paragraph', text: 'Da. Jedan dobar alat može uštedjeti pet do deset sati tjedno u odnosu na WhatsApp i Excel.' },
    ],
  },
  {
    slug: 'onboarding-novi-klijent',
    title: 'Onboarding novog klijenta - što napraviti u prvom tjednu',
    excerpt: 'Što napraviti u prvom tjednu s novim klijentom: upitnik, plan, prvi check-in i kako postaviti očekivanja.',
    category: 'Klijenti',
    categorySlug: 'klijenti',
    readTime: 6,
    publishedAt: '17. travnja 2026.',
    ...author,
    metaTitle: 'Onboarding novi klijent - checklista za trenere',
    metaDescription: 'Što napraviti u prvom tjednu s novim klijentom: upitnik, plan, prvi check-in i kako postaviti očekivanja.',
    cta: {
      text: 'UnitLift vodi klijenta kroz prvi tjedan. Pošalji link, klijent instalira aplikaciju i vidi plan. Probaj 14 dana besplatno.',
      btn: 'Vidi kako UnitLift organizira klijente →',
      href: '/kako-radi',
    },
    content: [
      { type: 'paragraph', text: 'Prvi tjedan s novim klijentom odlučuje o sljedećih šest mjeseci. Ako klijent odmah zna pravila igre, ostaje dulje.' },
      { type: 'paragraph', text: 'U ovom tekstu prolazimo što napraviti dan po dan: upitnik, plan, prvi check-in i kako postaviti očekivanja.' },
      { type: 'internal-link', text: '→ Što je check-in i kako ga postaviti', href: '/hr/blog/sto-je-check-in-online-coaching' },
      { type: 'internal-link', text: '→ Kako planovi treninga izgledaju online', href: '/hr/blog/planovi-treninga-online-klijenti' },

      { type: 'heading', text: 'Dan 0: pristup i pravila' },
      { type: 'list', items: [
        'Pošalji klijentu pristup aplikaciji ili mjestu za plan',
        'Objasni kad očekuješ poruke i kad je tjedni check-in',
        'Reci koliko dugo čekaš na odgovor s njegove strane',
        'Pošalji kratku uplatnicu ili potvrdu paketa',
      ]},

      { type: 'heading', text: 'Dan 1: upitnik i cilj' },
      { type: 'paragraph', text: 'Upitnik od 15 do 20 pitanja. Traje 15 minuta klijentu, dovoljno za postavljanje prvog plana.' },
      { type: 'list', items: [
        'Cilj: mršavljenje, snaga, zdravlje, sport',
        'Povijest ozljeda i bolova',
        'Iskustvo u teretani',
        'Koliko puta tjedno može trenirati',
        'Oprema kod kuće ili u teretani',
      ]},

      { type: 'heading', text: 'Dan 2–3: prvi plan treninga' },
      { type: 'paragraph', text: 'Prvi plan mora biti izvediv. Klijent mora moći završiti svaki trening bez osjećaja da ne razumije što radi.' },
      { type: 'paragraph', text: 'Uključi kratki video ili sliku za nove vježbe. Dodaj zamjensku vježbu za slučaj nedostatka opreme.' },

      { type: 'heading', text: 'Kraj prvog tjedna: mali check-in' },
      { type: 'paragraph', text: 'Pet pitanja koje ćeš ponavljati svaki tjedan. Klijent se navikne, ti dobiješ jasnu sliku kako mu ide.' },
      { type: 'internal-link', text: '→ Kad klijent posustane: kako ga zadržati', href: '/hr/blog/kako-zadrzati-online-klijenta' },

      { type: 'heading', text: 'Česta pitanja' },
      { type: 'subheading', text: 'Koliko dug upitnik?' },
      { type: 'paragraph', text: 'Ne duži od 15 minuta popunjavanja. Kraći upitnik znači da klijent stvarno odgovori na pitanja.' },
      { type: 'subheading', text: 'Moram li odmah poslati plan prehrane?' },
      { type: 'paragraph', text: 'Samo ako je dio paketa. Ako nije, jasno reci što je uključeno.' },
      { type: 'subheading', text: 'Što ako klijent ne popuni upitnik?' },
      { type: 'paragraph', text: 'Pošalji jedan podsjetnik. Ako i dalje ne popuni, nazovi direktno prije slanja plana.' },
      { type: 'subheading', text: 'Je li Zoom poziv obavezan?' },
      { type: 'paragraph', text: 'Nije, ali jedan kratki poziv od 15 minuta gradi povjerenje i ubrzava sve kasnije.' },
      { type: 'subheading', text: 'Kad poslati puni plan?' },
      { type: 'paragraph', text: 'Nakon upitnika, kratkog razgovora i prvog tjedna testa. Puni plan ima smisla kad znaš kako klijent stvarno trenira.' },
    ],
  },
]
