import type { BlogPost } from './types'

export const postsEn: BlogPost[] = [
  {
    slug: 'how-to-grow-your-client-base',
    title: 'How to Grow Your Online Client Base',
    excerpt: 'Nine proven tactics fitness coaches use to attract new clients without expensive ads or marketing agencies.',
    category: 'Guide',
    categorySlug: 'guide',
    readTime: 6,
    publishedAt: 'March 14, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'Building a client base is one of the biggest challenges every online fitness coach faces. The good news: you don\'t need expensive ads — you need the right strategy and consistency.' },
      { type: 'heading', text: '1. Define Your Ideal Client' },
      { type: 'paragraph', text: 'The most common beginner mistake is trying to work with "anyone." The narrower your focus — for example, women 35–45 who want to run their first half marathon — the better the conversion. Specialization builds trust.' },
      { type: 'heading', text: '2. Content That Solves Problems' },
      { type: 'paragraph', text: 'Instagram and TikTok don\'t pay you, but they can bring clients. Publish content that directly answers your ideal client\'s questions. Transformations, education, behind-the-scenes — all of it builds authority.' },
      { type: 'heading', text: '3. Leverage Existing Clients' },
      { type: 'paragraph', text: 'A satisfied client is your best marketing tool. Set up a referral system — offer a small discount for every new client they bring. Word-of-mouth still converts better than any ad.' },
      { type: 'heading', text: '4. Free Trial Period' },
      { type: 'paragraph', text: 'Offer 1–2 weeks of a free trial. This lowers the barrier to entry and lets a potential client feel the value of your program. If your product is good, conversion is a done deal.' },
      { type: 'heading', text: '5. Automate Onboarding' },
      { type: 'paragraph', text: 'When a new client arrives, an impressive onboarding is key. An automated welcome, clear plan, and quick responses build trust in the first week — and reduce drop-offs.' },
      { type: 'list', items: ['Respond to inquiries within 2 hours', 'Send a welcome pack (plan, questionnaire, expectations)', 'Set up automatic check-in reminders', 'Request a review after the first month'] },
      { type: 'quote', text: '"Don\'t wait for clients to come to you. Building a base is an active job — but with the right system, it becomes routine, not stress."' },
      { type: 'paragraph', text: 'With a combination of these tactics, most coaches we follow add 3–5 new clients in the first 90 days — without a single paid ad.' },
    ],
  },
  {
    slug: 'why-excel-is-not-enough',
    title: 'Why Excel Is No Longer Enough for Managing Clients',
    excerpt: 'Spreadsheets are great for beginners, but growing coaching practices inevitably need a proper solution — here\'s why.',
    category: 'Tools',
    categorySlug: 'tools',
    readTime: 4,
    publishedAt: 'March 11, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'I started with Excel. One sheet per client, formulas for calorie calculation, color-coding for each week. It looked clean — until I had 12 clients at the same time.' },
      { type: 'heading', text: 'The Problem Grows With Your Client Count' },
      { type: 'paragraph', text: 'Excel is great for structured data, but it\'s not designed for communication, real-time progress tracking, or automatic reminders. The more clients you have, the more time you lose on administration instead of coaching.' },
      { type: 'list', items: [
        'No automatic check-in reminders',
        'Clients can\'t access their plan on mobile',
        'Every plan change means manual updates',
        'No central place for communication',
        'Tracking payments is a separate spreadsheet',
      ]},
      { type: 'heading', text: 'What Actually Happens With Time' },
      { type: 'paragraph', text: 'A study we conducted with 50 coaches showed that the average coach with 15+ clients spends 8–12 hours per week on administration. That\'s almost a full workday — every week — spent on copy-paste, reminders, and searching through files.' },
      { type: 'quote', text: '"When I switched to a platform, I freed up 2 working days a week. That\'s 8 days a month now dedicated to clients — or rest."' },
      { type: 'heading', text: 'When Is the Right Time to Switch?' },
      { type: 'paragraph', text: 'If you have 5 or more active clients and feel that administration is eating your time, that\'s a clear signal. A system that scales with your business isn\'t a luxury — it\'s a prerequisite for growth.' },
      { type: 'paragraph', text: 'A good platform gives you automatic reminders, mobile access for clients, centralized communication, and financial overviews — all in one place. Excel can\'t do that.' },
    ],
  },
  {
    slug: 'tips-for-better-check-ins',
    title: '5 Tips for More Effective Client Check-ins',
    excerpt: 'How to structure weekly progress tracking so clients stay motivated and you stay informed — without losing hours.',
    category: 'Clients',
    categorySlug: 'clients',
    readTime: 5,
    publishedAt: 'March 7, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'The check-in is the heart of online coaching. Without regular and quality tracking, plans remain just theory. Here\'s how to make a check-in that actually works.' },
      { type: 'heading', text: '1. Standardize Your Questions' },
      { type: 'paragraph', text: 'Customized questions for every client sound nice, but in practice consume huge amounts of time. Create a standard questionnaire that covers everything important: body measurements, energy, sleep, plan adherence, subjective feeling.' },
      { type: 'heading', text: '2. Set Automatic Reminders' },
      { type: 'paragraph', text: 'Clients forget. That\'s not a bad sign — they\'re just busy. An automatic weekly reminder (Tuesday morning, for example) increases response rate from an average of 40% to 85%+. Let the system work for you.' },
      { type: 'heading', text: '3. Respond Within 24 Hours' },
      { type: 'paragraph', text: 'Clients who receive a quick check-in response stay longer and recommend their coach. Response speed directly affects satisfaction and perceived value. Calendar blocks for reviewing check-ins are mandatory.' },
      { type: 'heading', text: '4. Celebrate Progress, Not Just Results' },
      { type: 'paragraph', text: 'Kilograms and centimeters are one part of the story. A client who missed training last week due to illness but came back — that\'s progress. A weekly comment that recognizes effort builds loyalty.' },
      { type: 'heading', text: '5. Document Everything' },
      { type: 'paragraph', text: 'Every check-in is valuable data. Over 3–6 months, collected check-ins tell you which patterns repeat, when clients most often drop off, and what motivates them. That\'s the foundation for smart program adjustments.' },
      { type: 'quote', text: '"A client who feels tracked and seen stays on average 4x longer than one who just receives a plan by email."' },
      { type: 'list', items: [
        'Standardized questionnaire = less time, more data',
        'Automatic reminder = higher response rate',
        'Quick reply = greater satisfaction',
        'Celebrating effort = greater loyalty',
        'Documentation = smart coaching',
      ]},
    ],
  },
  {
    slug: 'how-to-set-your-prices',
    title: 'How to Set Your Prices as an Online Fitness Coach',
    excerpt: 'Stop undervaluing yourself. A pricing guide that takes into account value, market, and your business goals.',
    category: 'Growth',
    categorySlug: 'growth',
    readTime: 7,
    publishedAt: 'March 1, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'Pricing is often the question where coaches get most stuck. Fear of rejection, uncertainty about one\'s own worth, comparison to competitors — all of this leads to the same outcome: underpricing.' },
      { type: 'heading', text: 'Why Low Price Is Not an Advantage' },
      { type: 'paragraph', text: 'Counterintuitively, a price that\'s too low doesn\'t attract clients — it repels them. High perceived value of a service directly correlates with price. A client who pays €300/month for coaching invests more psychologically and engages more than one paying €50.' },
      { type: 'heading', text: 'The Pricing Formula' },
      { type: 'paragraph', text: 'Instead of copying competitors, calculate your minimum sustainable price:' },
      { type: 'list', items: [
        'Calculate how many hours per week you can dedicate to coaching',
        'Subtract admin, marketing, education (usually 30–40% of time)',
        'The rest is hours for clients — multiply by desired hourly rate',
        'Divide by the number of clients you can manage',
        'That\'s your minimum price per client',
      ]},
      { type: 'heading', text: 'Tiers: One Price Is Not Enough' },
      { type: 'paragraph', text: 'The most successful coaches offer 2–3 service levels. A basic package (plan + weekly check-in) at a lower price attracts a wider audience, while a premium package (daily availability, video calls, personalization) justifies a premium price. There should always be something more expensive than what the client is looking at.' },
      { type: 'heading', text: 'How to Communicate Your Price' },
      { type: 'paragraph', text: 'Price is never mentioned without context. "Coaching program is €199/month" means nothing. "Coaching program that has helped 40+ clients improve their form and train consistently, for €199/month" — that means something.' },
      { type: 'quote', text: '"Your price is a signal of how much you value your own work. Clients read that. Set it in line with the value you create — not with fear of rejection."' },
      { type: 'heading', text: 'Raise Prices for Existing Clients' },
      { type: 'paragraph', text: 'Once a year, with 30 days notice and a brief explanation of why (growing competencies, investing in tools, fewer clients for quality), raise prices by 10–20%. Most loyal clients accept this without issue.' },
    ],
  },
  {
    slug: 'automation-in-coaching',
    title: 'Automation in Fitness Coaching: What to Delegate, What to Keep',
    excerpt: 'Which tasks in your coaching business take the most time, and how to automate them without losing the personal touch.',
    category: 'Guide',
    categorySlug: 'guide',
    readTime: 6,
    publishedAt: 'February 14, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'Automation has a bad reputation in coaching. Coaches fear losing the "personal touch" and becoming robots that send mailers. But there\'s a fundamental difference between automating processes and automating relationships.' },
      { type: 'heading', text: 'What\'s Safe to Automate' },
      { type: 'paragraph', text: 'Administrative tasks should go on autopilot without exception. Anything predictable, repetitive, and not requiring your creativity or empathy is a candidate for automation.' },
      { type: 'list', items: [
        'Weekly check-in reminder',
        'Welcome message for a new client',
        'Payment reminder',
        'Sending plans on a fixed schedule',
        'Session booking confirmation',
      ]},
      { type: 'heading', text: 'What Should Never Be Automated' },
      { type: 'paragraph', text: 'Emotional moments are sacred. When a client achieves a goal — personal congratulation, not an automated email. When a client skips sessions — direct conversation, not a bot. Crises, plateaus, bad weeks — always you.' },
      { type: 'list', items: [
        'Responding to personal struggles and frustrations',
        'Congratulating achievements',
        'Adjusting plans in exceptional situations',
        'Video check-in calls',
        'Referrals and testimonials',
      ]},
      { type: 'heading', text: 'The "System Works, You Think" Principle' },
      { type: 'paragraph', text: 'The goal of automation isn\'t to reduce contact with clients — it\'s to free your cognitive resources for what really requires your presence. When the system sends reminders, you\'re free to focus on program quality, not message sending.' },
      { type: 'quote', text: '"Every hour I automate, I convert into one hour of better coaching for the clients who pay me for it. That\'s the only calculation that makes sense."' },
      { type: 'heading', text: 'Where to Start?' },
      { type: 'paragraph', text: 'Start with what you do every week: check-in reminder and weekly progress review. When that runs automatically, move to onboarding. Step by step, until only the tasks that require your full presence remain.' },
    ],
  },
  {
    slug: 'fitness-trainer-app',
    title: 'Fitness Trainer App: What to Look For',
    excerpt: 'More coaches are switching to digital tools — but not every app is equal. Here are the key features that should be on your checklist.',
    category: 'Tools',
    categorySlug: 'tools',
    readTime: 5,
    publishedAt: 'February 10, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'Demand for fitness trainer apps has never been higher. The rise of online coaching has led to dozens of solutions — from generic project management tools to specialized coaching platforms. How do you choose the right one?' },
      { type: 'heading', text: '1. Mobile App for Clients' },
      { type: 'paragraph', text: 'The most important item. Clients need to access their plan from mobile, submit check-ins, and communicate with the trainer without logging into a web browser. A dedicated iOS/Android app dramatically increases client engagement.' },
      { type: 'heading', text: '2. Integrated Progress Tracking' },
      { type: 'paragraph', text: 'The platform should automatically record check-in data over time and display trends. Coaches shouldn\'t manually copy values from one tool to another — everything must be in one place.' },
      { type: 'heading', text: '3. Training and Nutrition Plans' },
      { type: 'paragraph', text: 'The ability to create, duplicate, and share plans is key to scaling coaching. A good tool lets you build a template library you can personalize for each client in minutes.' },
      { type: 'heading', text: '4. In-Platform Communication' },
      { type: 'paragraph', text: 'WhatsApp is popular, but it\'s not suited for coaching — messages get lost, there\'s no context, no archive. A platform with built-in communication keeps all conversations organized and accessible.' },
      { type: 'heading', text: '5. Financial Tracking' },
      { type: 'paragraph', text: 'Payment tracking, subscription status per client, and revenue overview should be automatic. Manual financial management wastes precious time and increases the chance of error.' },
      { type: 'list', items: [
        'Mobile app for clients (iOS & Android)',
        'Automatic check-in and progress tracking',
        'Template library for plans',
        'Built-in communication (not WhatsApp)',
        'Financial tracking and revenue overview',
        'GDPR compliance and secure data storage',
      ]},
      { type: 'quote', text: '"UnitLift was designed with exactly this checklist in mind. Try it free for 14 days and see why it\'s the platform that grows alongside your business."' },
    ],
  },
  {
    slug: 'online-coaching-business-guide',
    title: 'How to Start an Online Coaching Business: From 0 to First Clients',
    excerpt: 'Step by step: from registration to first paying clients — what to do in the first week, first month, and first quarter.',
    category: 'Growth',
    categorySlug: 'growth',
    readTime: 8,
    publishedAt: 'February 3, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'An online coaching business can look like a complex machine — website, social media, plans, communication, payments. But the essence is simple: help someone achieve a goal, and charge for it. The rest comes gradually.' },
      { type: 'heading', text: 'Week 1: The Foundation' },
      { type: 'paragraph', text: 'The first thing isn\'t a website or Instagram profile — it\'s clarity. Define who you help (target audience), with what problem (specific outcome), and how (your method). Without that, everything else is random.' },
      { type: 'list', items: [
        'Define who your ideal client is',
        'Determine one specific transformation you offer',
        'Set up your coaching platform (registration takes 5 min)',
        'Create one package with a clear price',
      ]},
      { type: 'heading', text: 'Weeks 2–4: First Clients' },
      { type: 'paragraph', text: 'Your first clients don\'t come from ads — they come from your network. Send a message to 20–30 contacts who match your ideal client. Offer a free trial period. You only need 2–3 initial clients to get feedback and first reviews.' },
      { type: 'heading', text: 'Months 2–3: System and Growth' },
      { type: 'paragraph', text: 'When you have 3–5 paying clients, focus on systems that work without you: automatic onboarding, weekly check-ins, reminders. This frees up capacity for marketing and new clients.' },
      { type: 'heading', text: 'Most Common Mistakes' },
      { type: 'list', items: [
        'Too much time on design and branding, too little on sales',
        'Too-low price from fear of rejection',
        'Working without a system — manual everything, not scalable',
        'Not asking for reviews from satisfied clients',
        'Quitting too early — growth comes between months 3 and 6',
      ]},
      { type: 'quote', text: '"Every successful online trainer I know had a rough start. The difference is they continued long enough for the system to start working for them."' },
      { type: 'paragraph', text: 'UnitLift is designed exactly for this growth phase — from the first client to scaling. Setup takes less than 5 minutes, and the 14-day free trial gives you enough time to see the difference.' },
    ],
  },
  {
    slug: 'online-coaching-platform-guide',
    title: 'Why Online Fitness Coaches Choose Specialized Platforms Over Generic Tools',
    excerpt: 'Google Docs, Notion, and WhatsApp are free. But how much are they actually costing you in time and professionalism? An explanation for coaches considering the switch.',
    category: 'Tools',
    categorySlug: 'tools',
    readTime: 5,
    publishedAt: 'January 28, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'Generic tools have one big advantage: they\'re free (or cheap). That\'s why most coaches start with them. Pen for Google Doc, WhatsApp for communication, Revolut or PayPal for payments. It works — up to a point.' },
      { type: 'heading', text: 'The Problem of Fragmentation' },
      { type: 'paragraph', text: 'When working with 10+ clients, managing data scattered across 5–6 different tools becomes a serious problem. Client A sends questions via WhatsApp, client B via Instagram, client C via email. Check-ins are in a Google Form, plans in Docs, payments in Revolut. Where is everyone? What is everyone waiting for?' },
      { type: 'heading', text: 'What a Specialized Platform Actually Provides' },
      { type: 'list', items: [
        'Everything in one place — client, plan, communication, check-in, payment',
        'Automation that doesn\'t require your attention',
        'Professional impression — client has their own app, not a shared Docs file',
        'Data that accumulates and becomes valuable for coaching',
        'GDPR compliance and secure storage — no worrying about data privacy',
      ]},
      { type: 'heading', text: 'The Hidden Cost of Fragmentation' },
      { type: 'paragraph', text: 'One hour a day on administration is 365 hours a year — nearly 10 working weeks. If your service rate is €50/hour, that\'s €18,250 a year lost to copy-paste and organization. Platforms cost far less than that.' },
      { type: 'quote', text: '"Switching to UnitLift didn\'t just save me time — I started operating like a real business. Clients notice and stay longer."' },
      { type: 'paragraph', text: 'UnitLift is a platform built exclusively for online fitness coaches — it\'s not an adapted Notion, not an upgraded Google Sheet. Every feature exists because a coach asked for exactly that.' },
    ],
  },
  {
    slug: 'earn-more-as-online-fitness-trainer',
    title: 'How to Earn More as an Online Fitness Trainer Without More Hours',
    excerpt: 'An online trainer\'s income doesn\'t just depend on client count — it depends on systems, pricing, and how much time you spend per client.',
    category: 'Growth',
    categorySlug: 'growth',
    readTime: 6,
    publishedAt: 'January 20, 2026',
    author: 'Leon',
    authorRole: 'Personal trainer and owner of UnitLift',
    content: [
      { type: 'paragraph', text: 'There are two strategies for higher income: more clients or a higher price per client. Both work, but both have a prerequisite — a system that doesn\'t consume all your free time.' },
      { type: 'heading', text: 'Strategy 1: Optimize Revenue Per Client' },
      { type: 'paragraph', text: 'How many hours per week do you spend per client? Count everything — planning, communication, reviewing check-ins, administration. If the answer is more than 2 hours, you have room to optimize. With automation of routine tasks, that number drops to 30–45 minutes per client.' },
      { type: 'paragraph', text: 'That means with the same working hours, you can have twice as many clients — or reduce clients and increase service quality (and price).' },
      { type: 'heading', text: 'Strategy 2: Tiered Pricing' },
      { type: 'paragraph', text: 'One package means every client gets the same level of service — and pays the same price. Introducing 2–3 tiers (e.g., Basic, Pro, VIP) opens the market to self-selection. VIP clients pay premium for faster access, more frequent check-ins, and video calls. Same you, higher income.' },
      { type: 'heading', text: 'Strategy 3: Longer Client Retention' },
      { type: 'paragraph', text: 'Acquiring a new client costs 5–7x more than retaining an existing one. If the average client stays 3 months, increasing that to 6 months effectively doubles revenue without a single new client. The key is a system that monitors clients, identifies problems, and responds in time.' },
      { type: 'list', items: [
        'Automate routine → more clients, same hours',
        'Introduce tiered pricing → client chooses their service level',
        'Extend retention → less acquisition, higher LTV',
        'Charge for value, not hours → results aren\'t measured in hours',
        'Reinvest in tools that save you 5+ hours per week',
      ]},
      { type: 'quote', text: '"Income isn\'t a client scaling problem — it\'s a system optimization problem. Good coaches realize this in year two. We accelerate that to the first 60 days."' },
    ],
  },
]
