import type { BlogPost } from './types'

export const postsHr: BlogPost[] = [
  {
    slug: 'kako-povecati-bazu-klijenata',
    title: 'Kako povećati bazu online klijenata u 2025.',
    excerpt: 'Devet provjerenih taktika kojima fitness treneri privlače nove klijente bez skupih reklama i marketinških agencija.',
    category: 'Vodič',
    categorySlug: 'vodic',
    readTime: 6,
    publishedAt: '14. ožujka 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Izgradnja baze klijenata jedan je od najvećih izazova svakog online fitness trenera. Dobra vijest je da ti za to ne trebaju skupi oglasi — trebaju ti prava strategija i konzistentnost.' },
      { type: 'heading', text: '1. Definiraj svog idealnog klijenta' },
      { type: 'paragraph', text: 'Najčešća greška početnika je pokušaj da rade s "bilo kim". Što uži fokus — primjerice, žene 35–45 koje žele trčati prvi polumaraton — to bolja konverzija. Specijalizacija gradi povjerenje.' },
      { type: 'heading', text: '2. Sadržaj koji rješava probleme' },
      { type: 'paragraph', text: 'Instagram i TikTok tebe ne plaćaju, ali mogu dovesti klijente. Objavljuj sadržaj koji izravno odgovara na pitanja tvog idealnog klijenta. Transformacije, edukacija, iza scene — sve to gradi autoritet.' },
      { type: 'heading', text: '3. Iskoristi postojeće klijente' },
      { type: 'paragraph', text: 'Zadovoljni klijent je tvoj najbolji marketinški alat. Postavi sustav za preporuke — ponudi malj popust za svakog novog klijenta kojeg dovedu. Word-of-mouth i dalje konvertira bolje od svakog oglasa.' },
      { type: 'heading', text: '4. Besplatna probna sesija' },
      { type: 'paragraph', text: 'Ponudi 1–2 tjedna besplatnog probnog perioda. To snižava ulaznu barijeru i dozvoljava potencijalnom klijentu da osjeti vrijednost tvog programa. Ako je tvoj produkt dobar, konverzija je gotova stvar.' },
      { type: 'heading', text: '5. Automatizacija onboardinga' },
      { type: 'paragraph', text: 'Kada novi klijent dođe, impresionan onboarding je ključan. Automatiziranom dobrodošlicom, jasnim planom i brzim odgovorima gradi se povjerenje još u prvom tjednu — i smanjuje se odustajanje.' },
      { type: 'list', items: ['Odgovori na upit unutar 2 sata', 'Pošalji welcome paket (plan, upitnik, očekivanja)', 'Postavi automatski podsjetnik za check-in', 'Zatraži recenziju nakon prvog mjeseca'] },
      { type: 'quote', text: '"Nemoj čekati da klijenti dođu sami. Izgradnja baze je aktivni posao — ali s pravim sustavom, postaje rutina, ne stres."' },
      { type: 'paragraph', text: 'Kombinacijom ovih taktika, većina trenera koje pratimo dodaje 3–5 novih klijenata u prvih 90 dana — bez ijednog plaćenog oglasa.' },
    ],
  },
  {
    slug: 'zasto-excel-nije-dovoljan',
    title: 'Zašto Excel više nije dovoljan za vođenje klijenata',
    excerpt: 'Spreadsheetovi su dobri za početnike, ali rastuće coaching prakse nužno trebaju pravo rješenje — evo zašto.',
    category: 'Alati',
    categorySlug: 'alati',
    readTime: 4,
    publishedAt: '11. ožujka 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Počeo sam s Excelom. Jedan sheet za svakoga klijenta, formule za izračun kalorija, boja za svaki tjedan. Izgledalo je uredno — dok nisam imao 12 klijenata odjednom.' },
      { type: 'heading', text: 'Problem raste s brojem klijenata' },
      { type: 'paragraph', text: 'Excel je odličan za strukturirane podatke, ali nije dizajniran za komunikaciju, praćenje napretka u realnom vremenu ni automatske podsjetike. Što više klijenata imaš, to više vremena gubiš na administraciju umjesto na coaching.' },
      { type: 'list', items: [
        'Nema automatskih podsjetnika za check-in',
        'Klijenti ne mogu pristupiti planu s mobitela',
        'Svaka promjena u planu znači ručno ažuriranje',
        'Nema centralnog mjesta za komunikaciju',
        'Praćenje plaćanja je poseban spreadsheet',
      ]},
      { type: 'heading', text: 'Što se zapravo događa s vremenom' },
      { type: 'paragraph', text: 'Istraživanje koje smo napravili s 50 trenera pokazalo je da prosječan trener s 15+ klijenata troši 8–12 sati tjedno na administraciju. To je gotovo cijeli radni dan — svaki tjedan — koji ide na copy-paste, podsjetnike i traženje podataka u hrpi fajlova.' },
      { type: 'quote', text: '"Kad sam prešao na platformu, oslobodio sam 2 radna dana tjedno. To je 8 dana u mjesecu koji su sada posvećeni klijentima — ili odmoru."' },
      { type: 'heading', text: 'Kada je pravo vrijeme za promjenu?' },
      { type: 'paragraph', text: 'Ako imaš 5 i više aktivnih klijenata i osjećaš da administracija jede tvoje vrijeme, to je jasan signal. Sustav koji skalira s tvojim biznisom nije luksuz — to je preduvjet za rast.' },
      { type: 'paragraph', text: 'Dobra platforma ti daje automatske podsjetike, mobilni pristup klijentima, centraliziranu komunikaciju i financijske preglede — sve iz jednog mjesta. Excel to ne može.' },
      { type: 'internal-link', text: '→ Pogledaj kako UnitLift zamjenjuje Excel i WhatsApp za online fitness trenere', href: '/hr/software-za-online-fitness-trenere' },
    ],
  },
  {
    slug: 'savjeti-za-check-in-razgovore',
    title: '5 savjeta za učinkovitije check-in razgovore s klijentima',
    excerpt: 'Kako strukturirati tjedno praćenje napretka tako da klijenti budu motivirani, a ti informiran — bez gubitka sati.',
    category: 'Klijenti',
    categorySlug: 'klijenti',
    readTime: 5,
    publishedAt: '7. ožujka 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Check-in je srce online coachinga. Bez redovitog i kvalitetnog praćenja, planovi ostaju samo teorija. Evo kako napraviti check-in koji stvarno funkcionira.' },
      { type: 'heading', text: '1. Standardiziraj pitanja' },
      { type: 'paragraph', text: 'Prilagođena pitanja za svakog klijenta zvuče lijepo, ali u praksi troše ogromno vremena. Stvori standardni upitnik koji pokrije sve bitno: tjelesne mjere, energija, san, adherencija planu, subjektivni osjećaj.' },
      { type: 'heading', text: '2. Postavi automatski podsjetnik' },
      { type: 'paragraph', text: 'Klijenti zaboravljaju. To nije loš znak — jednostavno su zauzeti. Automatski tjedni podsjetnik (utorak ujutro, primjerice) povećava stopu odaziva s prosječnih 40% na 85%+. Neka sustav radi za tebe.' },
      { type: 'heading', text: '3. Odgovori unutar 24 sata' },
      { type: 'paragraph', text: 'Klijenti koji dobivaju brz odgovor na check-in ostaju dulje i preporučuju trenerom. Brzina odgovora direktno utječe na zadovoljstvo i percepciju vrijednosti. Blokovi za pregled check-inova u kalendaru su obvezni.' },
      { type: 'heading', text: '4. Slavi napredak, ne samo rezultate' },
      { type: 'paragraph', text: 'Kilogrami i centimetri su jedan dio priče. Klijent koji je prošli tjedan preskočio trening zbog bolesti, ali se vratio — to je napredak. Tjedni komentar koji prepoznaje trud gradi lojalnost.' },
      { type: 'heading', text: '5. Dokumentiraj sve' },
      { type: 'paragraph', text: 'Svaki check-in je dragocjen podatak. Kroz 3–6 mjeseci, prikupljeni check-inovi ti govore koji se obrasci ponavljaju, kada klijenti najčešće odustaju i što ih motivira. To je osnova za pametno prilagođavanje programa.' },
      { type: 'quote', text: '"Klijent koji se osjeća praćenim i viđenim ostaje prosječno 4x dulje od onog koji samo dobiva plan u mailu."' },
      { type: 'list', items: [
        'Standardiziran upitnik = manje vremena, više podataka',
        'Automatski podsjetnik = veći odaziv',
        'Brz odgovor = veće zadovoljstvo',
        'Praznovanje truda = veća lojalnost',
        'Dokumentacija = pametan coaching',
      ]},
    ],
  },
  {
    slug: 'kako-postaviti-cijene',
    title: 'Kako postaviti cijene kao online fitness trener',
    excerpt: 'Prestani se podcjenjivati. Vodič za postavljanje cijena koji uzima u obzir vrijednost, tržište i tvoje poslovne ciljeve.',
    category: 'Rast',
    categorySlug: 'rast',
    readTime: 7,
    publishedAt: '1. ožujka 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Pitanje cijena najčešće je ono pred kojim se treneri najviše blokiraju. Strah od odbijanja, neizvjesnost o vlastite vrijednosti, usporedba s konkurencijom — sve to vodi prema istom ishodu: podcjenjivanju.' },
      { type: 'heading', text: 'Zašto niska cijena nije prednost' },
      { type: 'paragraph', text: 'Kontraintuitivno, preniska cijena ne privlači klijente — odbija ih. Visoka percipirana vrijednost usluge direktno korelira s cijenom. Klijent koji plati 300 EUR/mj za coaching ulaže i psihološki se više angažira od onog koji plaća 50 EUR.' },
      { type: 'heading', text: 'Formula za postavljanje cijene' },
      { type: 'paragraph', text: 'Umjesto kopiranja konkurencije, izračunaj svoju minimalnu održivu cijenu:' },
      { type: 'list', items: [
        'Izračunaj koliko sati tjedno možeš posvetiti coachingu',
        'Oduzmi admin, marketing, edukaciju (obično 30–40% vremena)',
        'Ostalo su sati za klijente — pomnož s željenom satnicom',
        'Podijeli s brojem klijenata koje možeš voditi',
        'To je tvoja minimalna cijena po klijentu',
      ]},
      { type: 'heading', text: 'Tiers: jedna cijena nije dovoljna' },
      { type: 'paragraph', text: 'Najuspješniji treneri nude 2–3 razine usluge. Bazični paket (plan + tjedni check-in) za nižu cijenu privlači širu publiku, dok premium paket (dnevna dostupnost, video pozivi, personalizacija) opravdava premium cijenu. Uvijek treba postojati nešto skuplje od onog što klijent gleda.' },
      { type: 'heading', text: 'Kako komunicirati cijenu' },
      { type: 'paragraph', text: 'Cijena se nikad ne govori bez konteksta. "Coaching program je 199 EUR/mj" ništa ne znači. "Coaching program koji je pomogao 40+ klijenata da unaprijede formu i konzistentno vježbaju, za 199 EUR/mj" — to nešto znači.' },
      { type: 'quote', text: '"Tvoja cijena je signal koliko cijeniš vlastiti posao. Klijenti to čitaju. Postavi je u skladu s vrijednošću koju stvaraš — ne sa strahom od odbijanja."' },
      { type: 'heading', text: 'Povećaj cijene postojećim klijentima' },
      { type: 'paragraph', text: 'Jednom godišnje, uz najavu od 30 dana i kratko objašnjenje zašto (rast kompetencija, ulaganje u alate, manji broj klijenata zbog kvalitete), povećaj cijene za 10–20%. Većina lojalnih klijenata prihvaća to bez problema.' },
    ],
  },
  {
    slug: 'automatizacija-u-coachingu',
    title: 'Automatizacija u fitness coachingu: što delegirati, a što zadržati',
    excerpt: 'Koji zadaci u tvom coaching biznisu oduzimaju najviše vremena i kako ih automatizirati bez gubitka osobnog dodira s klijentom.',
    category: 'Vodič',
    categorySlug: 'vodic',
    readTime: 6,
    publishedAt: '14. veljače 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Automatizacija ima lošu reputaciju u coachingu. Treneri se boje da će izgubiti "osobni dodir" i postati roboti koji šalju mailers. Ali postoji fundamentalna razlika između automatizacije procesa i automatizacije odnosa.' },
      { type: 'heading', text: 'Što je sigurno automatizirati' },
      { type: 'paragraph', text: 'Administrativni zadaci bez izuzetka trebaju ići na auto-pilot. Sve što je predvidivo, ponavljajuće i ne zahtijeva tvoju kreativnost ili empatijakandidati su za automatizaciju.' },
      { type: 'list', items: [
        'Tjedni podsjetnik za check-in',
        'Welcome poruka za novog klijenta',
        'Podsjetnik za plaćanje',
        'Slanje planova po fiksnom rasporedu',
        'Potvrda rezervacije sesije',
      ]},
      { type: 'heading', text: 'Što nikad ne smije biti automatizirano' },
      { type: 'paragraph', text: 'Emocionalni momenti su sveti. Kada klijent postigne cilj — osobna čestitka, ne automatizirani email. Kada klijent preskače sesije — direktan razgovor, ne bot. Krize, plateau, loš tjedan — uvijek ti.' },
      { type: 'list', items: [
        'Odgovor na osobne borbe i frustracije',
        'Čestitka za dostignuće',
        'Prilagodba plana u izvanrednim situacijama',
        'Video check-in pozivi',
        'Preporuke i testimoniali',
      ]},
      { type: 'heading', text: 'Princip "sustav radi, ti misliš"' },
      { type: 'paragraph', text: 'Cilj automatizacije nije smanjiti kontakt s klijentima — nego osloboditi tvoje kognitivne resurse za ono što stvarno zahtijeva tvoju prisutnost. Kada sustav šalje podsjetike, ti si slobodan fokusirati se na kvalitetu programa, ne na slanje poruka.' },
      { type: 'quote', text: '"Svaki sat koji automatiziram, pretvorim u jedan sat boljeg coachinga za klijente koji mi to plaćaju. To je jedina računica koja ima smisla."' },
      { type: 'heading', text: 'Gdje početi?' },
      { type: 'paragraph', text: 'Počni s onim što radi svaki tjedan: podsjetnik za check-in i tjedni pregled napretka. Kada to radi automatski, prijeđi na onboarding. Korak po korak, dok ne ostanu samo oni zadaci koji zahtijevaju tvoju punu prisutnost.' },
    ],
  },
  {
    slug: 'aplikacija-za-fitness-trenere',
    title: 'Aplikacija za fitness trenere: što tražiti u 2025.',
    excerpt: 'Sve više trenera prelazi na digitalne alate — ali nije svaka aplikacija jednaka. Evo ključnih značajki koje trebaju biti na popisu.',
    category: 'Alati',
    categorySlug: 'alati',
    readTime: 5,
    publishedAt: '10. veljače 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Potražnja za aplikacijama za fitness trenere nikad nije bila veća. Rast online coachinga doveo je do pojave desetaka rješenja — od generičkih projektnih alata do specijaliziranih coaching platformi. Kako odabrati pravo?' },
      { type: 'heading', text: '1. Mobilna aplikacija za klijente' },
      { type: 'paragraph', text: 'Najvažnija stavka. Klijent mora moći pristupiti planu s mobitela, predati check-in i komunicirati s trenerom bez potrebe za prijavom u web-preglednik. Namjenska iOS/Android aplikacija drastično povećava angažman klijenta.' },
      { type: 'heading', text: '2. Integrirano praćenje napretka' },
      { type: 'paragraph', text: 'Platforma treba automatski bilježiti check-in podatke kroz vrijeme i prikazivati trendove. Trener ne smije ručno prepisivati vrijednosti iz jednog alata u drugi — sve mora biti na jednom mjestu.' },
      { type: 'heading', text: '3. Planovi treninga i prehrane' },
      { type: 'paragraph', text: 'Mogućnost kreiranja, dupliciranja i dijeljenja planova ključna je za skaliranje coachinga. Dobar alat ti dozvoljava izgradnju knjižnice predložaka koje možeš personalizirati za svakog klijenta u minutama.' },
      { type: 'heading', text: '4. Komunikacija unutar platforme' },
      { type: 'paragraph', text: 'WhatsApp je popularan, ali nije pogodan za coaching — poruke se gube, nema konteksta, nema arhive. Platforma s ugrađenom komunikacijom drži sve razgovore organiziranima i dostupnima.' },
      { type: 'heading', text: '5. Financijsko praćenje' },
      { type: 'paragraph', text: 'Praćenje plaćanja, status pretplate po klijentu i pregled prihoda trebaju biti automatski. Ručno vođenje financija oduzima dragocjeno vrijeme i povećava mogućnost greške.' },
      { type: 'list', items: [
        'Mobilna aplikacija za klijente (iOS & Android)',
        'Automatski check-in i praćenje napretka',
        'Knjižnica predložaka za planove',
        'Ugrađena komunikacija (ne WhatsApp)',
        'Financijsko praćenje i pregled prihoda',
        'GDPR sukladnost i sigurna pohrana podataka',
      ]},
      { type: 'quote', text: '"UnitLift je dizajniran upravo s ovim popisom na umu. Isprobaj 14 dana besplatno i uvjeri se zašto je to platforma koja raste zajedno s tvojim biznisom."' },
      { type: 'internal-link', text: '→ Saznaj više o softveru za online fitness trenere — što UnitLift nudi i kako početi', href: '/hr/software-za-online-fitness-trenere' },
    ],
  },
  {
    slug: 'online-coaching-biznis-vodic',
    title: 'Kako pokrenuti online coaching biznis: od 0 do prvih klijenata',
    excerpt: 'Korak po korak: od registracije do prvih plaćenih klijenata — što napraviti u prvom tjednu, prvom mjesecu i prvom kvartalu.',
    category: 'Rast',
    categorySlug: 'rast',
    readTime: 8,
    publishedAt: '3. veljače 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Online coaching biznis može izgledati kao kompleksna mašinerija — web stranica, društvene mreže, planovi, komunikacija, plaćanje. Ali suština je jednostavna: pomozi osobi da postigne cilj, i naplati za to. Ostatak dolazi postepeno.' },
      { type: 'heading', text: 'Tjedan 1: temelji' },
      { type: 'paragraph', text: 'Prva stvar nije web stranica ni Instagram profil — to je jasnoća. Definiraj kome pomažeš (ciljna skupina), s kojim problemom (specifičan ishod) i na koji način (tvoja metoda). Bez toga, sve ostalo je slučajno.' },
      { type: 'list', items: [
        'Definiraj tko je tvoj idealni klijent',
        'Odredi jednu specifičnu transformaciju koju nudiš',
        'Postavi coaching platformu (registracija traje 5 min)',
        'Kreiraj jedan paket s jasnom cijenom',
      ]},
      { type: 'heading', text: 'Tjedan 2–4: prvi klijenti' },
      { type: 'paragraph', text: 'Prve klijente ne dobivaš oglasima — dobivaš ih iz mreže. Pošalji poruku 20–30 kontakata koji odgovaraju tvom idealnom klijentu. Ponudi besplatno probno razdoblje. Treba ti samo 2–3 početnih klijenata da dobiješ povratnu informaciju i prve recenzije.' },
      { type: 'heading', text: 'Mjesec 2–3: sustav i rast' },
      { type: 'paragraph', text: 'Kad imaš 3–5 plaćenih klijenata, fokusiraj se na sustav koji radi bez tebe: automatski onboarding, tjedni check-inovi, podsjetnici. To ti oslobađa kapacitet za marketing i dolazak novih klijenata.' },
      { type: 'heading', text: 'Što se najčešće griješi?' },
      { type: 'list', items: [
        'Previše vremena na dizajn i branding, premalo na prodaju',
        'Preniska cijena iz straha od odbijanja',
        'Rad bez sustava — ručno sve, nije skalabilno',
        'Ne traženje recenzija od zadovoljnih klijenata',
        'Odustajanje prerano — rast dolazi između 3. i 6. mjeseca',
      ]},
      { type: 'quote', text: '"Svaki uspješan online trener kojeg poznajem imao je loš početak. Razlika je u tome što su nastavili dovoljno dugo da sustav počne raditi za njih."' },
      { type: 'paragraph', text: 'UnitLift je dizajniran upravo za ovu fazu rasta — od prvog klijenta do skaliranja. Postavljanje traje manje od 5 minuta, a 14-dnevno besplatno probno razdoblje daje ti dovoljno vremena da vidiš razliku.' },
    ],
  },
  {
    slug: 'online-coaching-treneri-platforma',
    title: 'Zašto online fitness treneri biraju specijalizirane platforme — a ne generičke alate',
    excerpt: 'Google Docs, Notion i WhatsApp su besplatni. Ali koliko zapravo koštaju tvoje vrijeme i profesionalnost? Objašnjenje za trenere koji razmišljaju o prelasku.',
    category: 'Alati',
    categorySlug: 'alati',
    readTime: 5,
    publishedAt: '28. siječnja 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Generički alati imaju jednu veliku prednost: besplatni su (ili jeftini). I zato većina početnih trenera počinje s njima. Pero za Google Doc, WhatsApp za komunikaciju, Revolut ili PayPal za plaćanje. Funkcionira — do određene točke.' },
      { type: 'heading', text: 'Problem fragmentacije' },
      { type: 'paragraph', text: 'Kada radiš s 10+ klijenata, upravljanje podacima rasutim po 5–6 različitih alata postaje ozbiljan problem. Klijent A pitanje šalje WhatsAppom, klijent B Instagramom, klijent C mailom. Check-inovi su u Googleovom obrascu, planovi u Docsu, plaćanja u Revolutu. Gdje je tko? Što tko čeka?' },
      { type: 'heading', text: 'Što specijalizirana platforma zapravo donosi' },
      { type: 'list', items: [
        'Sve na jednom mjestu — klijent, plan, komunikacija, check-in, plaćanje',
        'Automatizacija koja ne zahtijeva tvoju pozornost',
        'Profesionalan dojam — klijent ima svoju aplikaciju, ne dijeli Docs dokument',
        'Podaci koji se akumuliraju i postaju vrijedni za coaching',
        'GDPR sukladnost i sigurna pohrana — ne brigeš se za privatnost podataka',
      ]},
      { type: 'heading', text: 'Trošak fragmentacije je skriven' },
      { type: 'paragraph', text: 'Sat vremena dnevno na administraciju je 365 sati godišnje — gotovo 10 radnih tjedana. Ako je tvoja cijena usluge 50 EUR/sat, to je 18.250 EUR godišnje izgubljenih u copy-paste i organizaciji. Platforme koštaju daleko manje od toga.' },
      { type: 'quote', text: '"Prelaskom na UnitLift nisam samo uštedio vrijeme — počeo sam djelovati kao pravi biznis. Klijenti to primjete i ostaju dulje."' },
      { type: 'paragraph', text: 'UnitLift je platforma napravljena isključivo za online fitness trenere — nije prilagođeni Notion, nije nadograđeni Google Sheet. Svaka funkcija postoji jer je trener tražio upravo to.' },
    ],
  },
  {
    slug: 'kako-zaraditi-vise-kao-online-fitness-trener',
    title: 'Kako zaraditi više kao online fitness trener bez više radnih sati',
    excerpt: 'Prihod online trenera ne ovisi samo o broju klijenata — ovisi o sustavima, cijenama i tome koliko vrijemena trošiš na svaki klijent.',
    category: 'Rast',
    categorySlug: 'rast',
    readTime: 6,
    publishedAt: '20. siječnja 2025.',
    author: 'Leon',
    authorRole: 'Osobni trener i vlasnik UnitLift-a',
    content: [
      { type: 'paragraph', text: 'Postoje dvije strategije za veći prihod: više klijenata ili veća cijena po klijentu. Obje funkcioniraju, ali obje imaju preduvjet — sustav koji ti ne troši svo slobodno vrijeme.' },
      { type: 'heading', text: 'Strategija 1: Optimiziraj prihod po klijentu' },
      { type: 'paragraph', text: 'Koliko sati tjedno provodiš po klijentu? Uračunaj sve — planiranje, komunikaciju, pregled check-inova, administraciju. Ako je odgovor više od 2 sata, imaš prostor za optimizaciju. Automatizacijom rutine, taj broj pada na 30–45 minuta po klijentu.' },
      { type: 'paragraph', text: 'To znači da s istim brojem radnih sati možeš imati dvostruko više klijenata — ili smanjiti klijente i povećati kvalitetu usluge (i cijenu).' },
      { type: 'heading', text: 'Strategija 2: Tiered pricing' },
      { type: 'paragraph', text: 'Jedan paket znači da svaki klijent dobiva istu razinu usluge — i plaća istu cijenu. Uvođenjem 2–3 razine (npr. Basic, Pro, VIP) otvoriš tržištu mogućnost da sam odabere. VIP klijenti plaćaju premium za brži pristup, češće provjere i video pozive. Isti ti, veći prihod.' },
      { type: 'heading', text: 'Strategija 3: Dulje zadržavanje klijenata' },
      { type: 'paragraph', text: 'Stjecanje novog klijenta košta 5–7x više od zadržavanja postojećeg. Ako prosječan klijent ostaje 3 mjeseca, povećanje na 6 mjeseci de facto udvostručuje prihod bez ijednog novog klijenta. Ključ je sustav koji prati klijenta, prepoznaje probleme i reagira na vrijeme.' },
      { type: 'list', items: [
        'Automatiziraj rutinu → više klijenata, isti sati',
        'Uvedite tiered pricing → klijent sam bira nivo usluge',
        'Produlji zadržavanje → manje akvizicije, veći LTV',
        'Naplati vrijednost, ne sate → rezultati se ne mjere satima',
        'Reinvestiraj u alate koji ti štede 5+ sati tjedno',
      ]},
      { type: 'quote', text: '"Prihod nije problem skaliranja broja klijenata — to je problem optimizacije sustava. Dobri treneri to shvate u drugoj godini. Mi to ubrzavamo na prvih 60 dana."' },
    ],
  },
]
